mongo:
  connection: "mongodb://localhost:27017"
  database: "payment"
redis:
  host: "localhost"
  port: 6379
  db: 0
  username: ""
  password: ""
logger:
  level: "trace"
  caller: true
  encoding: "json"
  development: true